version: "3.9"
services:
  # backend:
  #   container_name: fanicon-backend
  #   build: ./backend/
  #   networks:
  #     - fanicon
  #   environment:
  #     - DATASOURCE=postgres
  #     - ENABLE_FLYWAY=true
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:8080

  frontend:
    # container_name: fanicon-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: image-dev
    # ports:
    #   - 80:80
    #   - 443:443
    # depends_on: 
    #   - backend
    network_mode: host
    volumes:
      - type: bind
        source: ./frontend/html
        target: /etc/nginx/html
        consistency: consistent

  postgres:
    # container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fanicon
    # ports:
    #   - 5432:5432
    network_mode: host
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    # container_name: pgadmin
    image: dpage/pgadmin4:5.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
      - PGADMIN_DEFAULT_PASSWORD=secret
    # ports:
    #   - 5050:5050
    network_mode: host
    volumes:
      - pgadmin-data:/root/.pgadmin
    depends_on:
      - postgres


volumes:
  postgres-db:
  pgadmin-data:
        
