version: "3.9"
services:
  frontend:
    build: ./frontend/
    ports:
      - 80:80
      - 443:443

  backend:
    build: ./backend/
    networks:
      - fanicon
    environment:
      - DATASOURCE=postgres
      - REDIS=redis
      - ENABLE_FLYWAY=true

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fanicon
    ports:
      - 5432:5432
    networks:
      - fanicon
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.2
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
        - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
        - 5050:80
    networks:
        - fanicon
    volumes:
        - pgadmin-data:/root/.pgadmin
    depends_on:
        - postgres

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - fanicon
    volumes:
      - redis-data:/data


networks:
  fanicon:
    driver: bridge

volumes:
  postgres-db:
  pgadmin-data:
  redis-data:
        
