name: test and deploy

# Controls when the action will run.
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build and test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and test with Gradle
        run: |
          cd backend
          ./gradlew build
          
  create_backend_image:
    name: Push backend Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build files
        run: |
          cd backend
          ./gradlew bootJar
      - name: Build and Push Image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./backend/Dockerfile
          repository: cedigasser/fanicon/fanicon-backend
          path: ./backend
          tags: latest

  create_frontend_image:
    name: Push frontend Docker image to the GitHub Packages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push Image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./frontend/Dockerfile
          repository: cedigasser/fanicon/fanicon-frontend
          path: ./frontend
          tags: latest
